apiVersion: v1
kind: ReplicationController
metadata: {name: busybox-sleep-perf}
spec:
  replicas: 1
  selector: {name: busybox-sleep-perf}
  template:
    metadata:
      labels: {name: busybox-sleep-perf}
    spec:
      containers:
      - args: [sleep, '1000000']
        image: busybox
        name: busybox
