# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-29 13:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projecthandler', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='validated',
            field=models.BooleanField(default=False),
        ),
    ]
