# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-03 09:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projecthandler', '0002_project_validated'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='info',
            field=models.TextField(default='No info'),
        ),
    ]
