# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-03 09:43
from __future__ import unicode_literals

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('projecthandler', '0003_project_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='data_project',
            field=jsonfield.fields.JSONField(default={'nsd': [], 'vld': [], 'vnfd': []}),
        ),
    ]
