# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-04 07:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('projecthandler', '0004_project_data_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='data_project',
            field=jsonfield.fields.JSONField(default={'nsd': {}, 'vld': {}, 'vnfd': {}, 'vnffgd': {}}),
        ),
        migrations.AlterField(
            model_name='project',
            name='updated_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
