# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-03-15 12:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Deployment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=20)),
                ('profile', jsonfield.fields.JSONField(default={})),
                ('project_name', models.CharField(default='', max_length=20)),
                ('project_id', models.CharField(default='', max_length=20)),
                ('creator_name', models.CharField(default='', max_length=20)),
                ('creator_id', models.CharField(default='', max_length=20)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(default='', max_length=20)),
            ],
        ),
    ]
